# Generated by Django 5.2.4 on 2025-07-31 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0002_alter_todolist_created_at_alter_todolist_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': '댓글', 'verbose_name_plural': '댓글 목록'},
        ),
    ]
