# Generated by Django 5.2.4 on 2025-08-04 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0003_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ToDoList/%Y/%m/%d', verbose_name='이미지'),
        ),
    ]
