# Generated by Django 5.2.4 on 2025-08-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0004_todolist_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='ToDoList/%Y/%m/%d/thumbnail', verbose_name='썸네일'),
        ),
    ]
